In [2]:
import cv2
from PIL import Image
import numpy as np

In [3]:
image = cv2.imread('C:\QRcodePy\QRtest.png')

In [4]:
QRCodeDetector = cv2.QRCodeDetector()

In [5]:
detected, points, straight_QR = QRCodeDetector.detectAndDecode(image)

In [6]:
detected

'2021-11-4077-01'

In [7]:
# decodedText

In [8]:
points

array([[[379., 586.],
        [452., 586.],
        [452., 659.],
        [379., 659.]]], dtype=float32)

In [9]:
points = np.array(points, dtype=np.int32)

points

array([[[379, 586],
        [452, 586],
        [452, 659],
        [379, 659]]])

In [10]:
len(points)

1

In [ ]:
if points is not None:
    nrOfPoints = len(points)
    
    for i in range(nrOfPoints):
        nextPointIndex = (i+1) % nrOfPoints
        cv2.line(image, tuple(points[i][0]), tuple(points[nextPointIndex][0]), (255,0,0), 5)
        print(decodedText)
 
    cv2.imshow("Image", image)
    cv2.waitKey(0)
    cv2.destroyAllWindows() 
else:
    print("QR code not detected")

['2021-11-4077-01', '']


In [11]:
points[0][0]

array([379, 586])

In [12]:
tuple(points[0][0])

(379, 586)